"""score: add nlarge_tick_hit & nsmall_tick_hit for pp calculator

Revision ID: dc4d25c428c7
Revises:
Create Date: 2025-07-29 01:43:40.221070

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dc4d25c428c7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("nlarge_tick_hit", sa.Integer(), nullable=True))
    op.add_column("scores", sa.Column("nsmall_tick_hit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "nsmall_tick_hit")
    op.drop_column("scores", "nlarge_tick_hit")
    # ### end Alembic commands ###
